version: "3.7"

services:
  server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - ./:/app
    command: go run ./src
    ports:
      - "127.0.0.1:7070:7070"
    env_file:
      - ./configurations.env
    depends_on:
      - scylla
    links:
      - scylla

  client:
    build: 
      context: ./
      dockerfile: ./docker/client/Dockerfile
    volumes: 
      - ./client/:/app
    environment:
      - REACT_APP_PORT=3000
    command: npm start
    ports:
      - "127.0.0.1:3000:3000"
    links:
      - server

  scylla:
    build:
      context: ./
      dockerfile: ./docker/scylladb/Dockerfile