version: "3.7"

services:
  server:
    build:
      context: ./
    volumes:
      - ./:/app
    command: go run ./src
    ports:
      - "127.0.0.1:7070:7070"
    env_file:
      - ./configurations.env

  scylla:
    image: scylladb/scylla:3.0.10
    volumes:
      - ./data/jtalk-scylla:/var/lib/scylla

