openapi: "3.0.0"
info:
  title: JTalk Restful API Service
  version: 0.0.1
servers:
  - url: http://127.0.0.1:7070
paths:
  /conversations/author/{author_id}:
    get:
      operationId: findConversationsByAuthor
      summary: Find conversations by author
      parameters:
          - in: path
            name: author_id
            required: true
            schema:
              type: integer
              example: 1
      responses:
        '200':
          description: The author's conversation list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
  /conversations/messages/{conversation_id}:
    get:
      operationId: findMessagesByConversation
      summary: Find messages by conversation
      parameters:
          - in: path
            name: conversation_id
            required: true
            schema:
              type: integer
              example: 1
      responses:
        '200':
          description: The message list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/message'
components:
  schemas:
    message:
      type: object
      properties:
        conversation_id:
          type: integer
        message_id:
          type: integer
        author_id:
          type: integer
        content:
          type: string
        created_at:
          type: integer
